package org.sitefolder.client;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.ConfigurableApplicationContext;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Configuration
@ComponentScan(basePackages = {"org.sitefolder"})
@SpringBootApplication
//@Import(RepositoryRestMvcConfiguration.class)
//@Import(IDConfiguration.class)
@EnableAutoConfiguration
public class ClientApplication {
 
	public static void main(String[] args) {
		ConfigurableApplicationContext ctx = SpringApplication.run(ClientApplication.class, args);
		
		AppTests appTests = ctx.getBean(AppTests.class);
		appTests.runTest();
		
		
		System.out.println("test");
		System.out.println("test");
		System.out.println("test");
		System.out.println("test");
		System.out.println("test");
	}

}
